### ISSUE TITLE
TypeError in 1.2.0

### ISSUE THREAD

**Issue by mjackson** [babel-plugins/babel-plugin-object-assign#4]
I tried updating the router to use 1.2.0 of this plugin but get the following error:

```
$ npm run build

> react-router@1.0.0-beta2 build /Users/michael/Projects/react-router
> scripts/build.sh


TypeError: undefined is not a function
    at exports.default (/Users/michael/Projects/react-router/node_modules/babel-plugin-object-assign/lib/index.js:11:10)
    at Function.memoisePluginContainer (/Users/michael/Projects/react-router/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:46:23)
    at PluginManager.add (/Users/michael/Projects/react-router/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:131:30)
    at File.buildTransformers (/Users/michael/Projects/react-router/node_modules/babel-core/lib/babel/transformation/file/index.js:290:21)
    at new File (/Users/michael/Projects/react-router/node_modules/babel-core/lib/babel/transformation/file/index.js:148:10)
    at TransformerPipeline.transform (/Users/michael/Projects/react-router/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:96:16)
    at Object.exports.transform (/Users/michael/Projects/react-router/node_modules/babel/bin/babel/util.js:33:22)
    at Object.exports.compile (/Users/michael/Projects/react-router/node_modules/babel/bin/babel/util.js:41:18)
    at write (/Users/michael/Projects/react-router/node_modules/babel/bin/babel/dir.js:16:21)
    at handleFile (/Users/michael/Projects/react-router/node_modules/babel/bin/babel/dir.js:37:7)
```

Forgive me for not being adept at deciphering babel plugin error messages. :P

**Comment by mjackson** [comment]
ah, nm. I think I was running an old version or something. Works fine now.
