### ISSUE TITLE
Plugin is not defined

### ISSUE THREAD

**Issue by BerkeleyTrue** [babel-plugins/babel-plugin-object-assign#5]
Just tried running `npm install` on master for React-Router, which makes use of this project. It throws during build step using 1.2.0 of this package

```
/Users/berkeley/node/react/router/node_modules/babel-plugin-object-assign/lib/index.js:11
  return new Plugin("object-assign", {
         ^
TypeError: undefined is not a function
    at exports.default (/Users/berkeley/node/react/router/node_modules/babel-plugin-object-assign/lib/index.js:11:10)
    at Function.memoisePluginContainer (/Users/berkeley/node/react/router/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:46:23)
    at PluginManager.add (/Users/berkeley/node/react/router/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:131:30)
    at File.buildTransformers (/Users/berkeley/node/react/router/node_modules/babel-core/lib/babel/transformation/file/index.js:290:21)
    at new File (/Users/berkeley/node/react/router/node_modules/babel-core/lib/babel/transformation/file/index.js:148:10)
    at TransformerPipeline.transform (/Users/berkeley/node/react/router/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:96:16)
    at Object.exports.transform (/Users/berkeley/node/react/router/node_modules/babel/bin/babel/util.js:33:22)
    at Object.exports.compile (/Users/berkeley/node/react/router/node_modules/babel/bin/babel/util.js:41:18)
    at write (/Users/berkeley/node/react/router/node_modules/babel/bin/babel/dir.js:16:21)
    at handleFile (/Users/berkeley/node/react/router/node_modules/babel/bin/babel/dir.js:37:7)
```

**Comment by BerkeleyTrue** [comment]
Actually just wiped my node_modules directory and started fresh. It may have been I had an older version of babel.
