### ISSUE TITLE
Module build failed: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by luqin** [babel-plugins/babel-plugin-object-assign#9]
```
Module build failed: TypeError: undefined is not a function

at exports.default (/node_modules/babel-plugin-object-assign/lib/index.js:11:10)
    at Function.memoisePluginContainer (/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:46:23)
    at PluginManager.add (/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:130:30)
    at File.buildTransformers (/node_modules/babel-core/lib/babel/transformation/file/index.js:281:21)
    at new File (/node_modules/babel-core/lib/babel/transformation/file/index.js:148:10)
    at TransformerPipeline.transform (/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:87:16)
    at transpile (/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/node_modules/babel-loader/index.js:43:24)
```

**Comment by loganfsmyth** [comment]
@luqin What version of babel are you using?

@JedWatson It looks like this is now using `new Plugin` from `v5.6.0`, but the peerDependency says `>=5.2.0`.

**Comment by luqin** [comment]
@loganfsmyth babel 5.4.

**Comment by luqin** [comment]
@loganfsmyth The error was gone when I I upgraded babel to 5.8.3.

**Comment by loganfsmyth** [comment]
Yeah it looks like this module now requires >=5.6.0

**Comment by luqin** [comment]
@loganfsmyth :+1:

**Comment by JedWatson** [comment]
Sorry about that - just fixed the minimum babel version required in `peerDependencies` so this won't cause confusion again.
